services:
  foto_obhodov:
    build: .
    container_name: foto_obhodov
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Проброс папки с фото
      - /mnt/userdata/camera:/mnt/userdata/camera
      # Проброс папки проекта
      - /root/projects/foto_obhodov:/app
    environment:
      - TZ=Europe/Moscow
    network_mode: host
